# Site settings
title: Sanghyun Kim
description: A blog about Sanghyun Kim a.k.a ggory15
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanghyun Kim
user_description: 
user_title: Ph.d Candidate (Robotics)
email: ggory15@snu.ac.kr
#twitter_username: lorem_ipsum
github_username: "ggory15"
gplus_username:  "ggory15"

# Google-analytics
google-analytics:""
  id: "ggory15"

exclude: ['package.json', 'src' , 'node_modules']
